version: '3.8'
services:
  db1:
    image: mariadb:10.6
    volumes:
      - /db/mariadb-1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    container_name: mariadb-1
    restart: always

  app-backend:
    image: shoeshop:v1
    ports: 
      - "8081:8080"
    container_name: shoeshop_1
    restart: always

